import Head from 'next/head'
import Link from 'next/dist/client/link'
import { blogPosts } from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        </main>

        <div>
          {blogPosts.map((item) => {
            return (
              <div key={item.tako}>
              <div>
                <Link href={`/blog/${item.tako}`}>
                  <a>{item.title}</a>
                </Link>
              </div>
              <div>{item.date}</div>
            </div>
            )
          })}

          {console.log('blog post items',blogPosts)}
        </div>
    </div>
  )
}
